name: Build
on:
  - push
  - workflow_dispatch
jobs:
  build:
    name: Build Tweak
    runs-on: macOS-latest
    env:
      THEOS: theos
    steps:
        - name: Checkout
          uses: actions/checkout@master
        - name: Install Dependencies
          run: brew install ldid xz
        - name: Setup Theos
          uses: actions/checkout@master
          with:
            repository: theos/theos
            ref: 487d9bd0113173ade74693b625d871e42df6df1c
            path: theos
            submodules: recursive
        - name: Download SDKs
          run: |
            curl -LO https://github.com/theos/sdks/releases/download/master-146e41f/iPhoneOS15.6.sdk.tar.xz
            TMP=$(mktemp -d)
            tar -xf iPhoneOS15.6.sdk.tar.xz -C $TMP
            mv $TMP/iPhoneOS15.6.sdk theos/sdks
            rm -r iPhoneOS15.6.sdk.tar.xz $TMP
        - name: Build Package
          id: build_package
          run: |
            make package FINALPACKAGE=1 messages=yes
            echo "::set-output name=package::$(ls -t packages | head -n1)"
        - name: Upload Artifact
          uses: actions/upload-artifact@v4.3.4
          with:
            path: packages
